// Code generated by ogen, DO NOT EDIT.
package oas

type CreateQuoteRes interface {
	createQuoteRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type GetProductRes interface {
	getProductRes()
}

type ListCustomerBranchesRes interface {
	listCustomerBranchesRes()
}

type ListOrderInvoicesRes interface {
	listOrderInvoicesRes()
}

type ListOrderShipmentsRes interface {
	listOrderShipmentsRes()
}

type SearchProductsRes interface {
	searchProductsRes()
}

type SetActiveBranchRes interface {
	setActiveBranchRes()
}
