// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateQuoteOperation          OperationName = "CreateQuote"
	GetOrderOperation             OperationName = "GetOrder"
	GetProductOperation           OperationName = "GetProduct"
	ListCustomerBranchesOperation OperationName = "ListCustomerBranches"
	ListOrdersOperation           OperationName = "ListOrders"
	ListQuotesOperation           OperationName = "ListQuotes"
	SearchProductsOperation       OperationName = "SearchProducts"
	SetActiveBranchOperation      OperationName = "SetActiveBranch"
)
