// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	ContactUsOperation            OperationName = "ContactUs"
	CreateQuoteOperation          OperationName = "CreateQuote"
	GetActiveBranchOperation      OperationName = "GetActiveBranch"
	GetInvoiceReportOperation     OperationName = "GetInvoiceReport"
	GetOrderOperation             OperationName = "GetOrder"
	GetPackingListReportOperation OperationName = "GetPackingListReport"
	GetProductOperation           OperationName = "GetProduct"
	GetQuoteOperation             OperationName = "GetQuote"
	GetRecentPurchasesOperation   OperationName = "GetRecentPurchases"
	ListCustomerBranchesOperation OperationName = "ListCustomerBranches"
	ListInvoicesOperation         OperationName = "ListInvoices"
	ListOrdersOperation           OperationName = "ListOrders"
	ListQuotesOperation           OperationName = "ListQuotes"
	SearchProductsOperation       OperationName = "SearchProducts"
	SetActiveBranchOperation      OperationName = "SetActiveBranch"
)
