// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateQuoteOperation          OperationName = "CreateQuote"
	GetOrderOperation             OperationName = "GetOrder"
	GetProductOperation           OperationName = "GetProduct"
	ListBranchOrdersOperation     OperationName = "ListBranchOrders"
	ListCustomerBranchesOperation OperationName = "ListCustomerBranches"
	ListOrderInvoicesOperation    OperationName = "ListOrderInvoices"
	ListOrderShipmentsOperation   OperationName = "ListOrderShipments"
	SearchProductsOperation       OperationName = "SearchProducts"
	SetActiveBranchOperation      OperationName = "SetActiveBranch"
)
