// Code generated by ogen, DO NOT EDIT.
package oas

type CreateQuoteRes interface {
	createQuoteRes()
}

type GetActiveBranchesRes interface {
	getActiveBranchesRes()
}

type GetInvoiceReportRes interface {
	getInvoiceReportRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type GetPackingListReportRes interface {
	getPackingListReportRes()
}

type GetProductRes interface {
	getProductRes()
}

type GetQuoteRes interface {
	getQuoteRes()
}

type ListCustomerBranchesRes interface {
	listCustomerBranchesRes()
}

type ListOrdersRes interface {
	listOrdersRes()
}

type ListQuotesRes interface {
	listQuotesRes()
}

type SearchProductsRes interface {
	searchProductsRes()
}

type SetActiveBranchRes interface {
	setActiveBranchRes()
}
